### ISSUE TITLE
Стили услуг на странице `.services-page.html`

### ISSUE THREAD

**Issue by foxhable** [aaccent/sovetnik_layout#22]
Эту секцию нужно изменить

<details><summary>Скрин секции</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/36298346/bf788934-858d-4caa-95ed-caf5872fff9c)
</details> 

То количество услуг в макете - это не реальное количество услуг. Их может быть меньше или больше, они могут увеличиваться или пропадать. От-того текущая реализация сетки не является гибким решением. Нужно переделать:
1. Убрать библиотеку Masonry
2. Дать `.services-section__grid` стили
```css
.services-section__grid {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 20px;
}
```
3. Подрезать здесь строки
https://github.com/aaccent/sovetnik_layout/blob/9740ef5fc7c7ceb989cc2b0b6aa2d49d00c0767b/src/scss/services-page.scss#L45-L51
```diff 
&__block {
-    margin: 0 0 1.25rem;
-    width: calc((100% - 2.5rem) / 3);
    &_full-width {
-        width: calc(2 * (100% - 2.5rem) / 3 + 1.25rem);
    }
}
```
4. Увеличить количество строк у элементов до 6
```css
.services-section__block {
  grid-row: span 6;
}
```
5. Добавить три класса:
```css
.services-section__block--horizontal {
  grid-column: span 2;
}
.services-section__block--horizontal-wide {
  grid-column: span 3;
}
.services-section__block--vertical {
  grid-row: span 7;
}
```
6. Раскидать по элементам
```html
<div class="services-section__block services-block services-section__block--vertical"></div>
<div class="services-section__block services-block services-section__block--horizontal-wide"></div>
<div class="services-section__block services-block services-section__block--vertical"></div>
<div class="services-section__block services-block services-section__block--vertical"></div>
<div class="services-section__block services-block"></div>
<div class="services-section__block services-block services-section__block--horizontal-wide"></div>
<div class="services-section__block services-block"></div>
<div class="services-section__block services-block"></div>
<div class="services-section__block services-block"></div>
<div class="services-section__block services-block"></div>
```

В последствии сборщик сделает возможнсть добавления классов через админку во время создания категории

И мобилку после этого не забудь поправить
